// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5IPA1nsb_zm8Bk93Y4FypBdyV1DRNcNQ',
    appId: '1:187301807758:web:4713b498c7ce5dbbc0ebdf',
    messagingSenderId: '187301807758',
    projectId: 'health-tick-526e4',
    authDomain: 'health-tick-526e4.firebaseapp.com',
    storageBucket: 'health-tick-526e4.firebasestorage.app',
    measurementId: 'G-DTSTQEHVKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSECDDk3de4ExOJNgAAnYbXeQTDfkxO1M',
    appId: '1:187301807758:android:d233974605383fdec0ebdf',
    messagingSenderId: '187301807758',
    projectId: 'health-tick-526e4',
    storageBucket: 'health-tick-526e4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5IPA1nsb_zm8Bk93Y4FypBdyV1DRNcNQ',
    appId: '1:187301807758:web:eb7ae5e5fbe2889bc0ebdf',
    messagingSenderId: '187301807758',
    projectId: 'health-tick-526e4',
    authDomain: 'health-tick-526e4.firebaseapp.com',
    storageBucket: 'health-tick-526e4.firebasestorage.app',
    measurementId: 'G-BS5JR1GJMW',
  );
}
